-- Phase 3: store generated tailored CV versions. The raw master CV is intentionally not persisted here.

create table if not exists public.cv_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id text not null,
  source_cv_name text,
  format text not null,
  emphasis text not null,
  model text not null,
  projected_alignment integer,
  fact_lock_passed boolean not null default false,
  document jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists cv_versions_user_job_created_idx on public.cv_versions(user_id, job_id, created_at desc);

alter table public.cv_versions enable row level security;

drop policy if exists "Users can read own CV versions" on public.cv_versions;
create policy "Users can read own CV versions"
on public.cv_versions for select
to authenticated
using (auth.uid() = user_id);

-- Writes are performed by the protected tailor-cv Edge Function using the secret/service key.
