-- Phase 4: persistent application tracker + generated application packages.

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id text not null,
  job_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'Ready to apply',
  deadline date,
  applied_at date,
  follow_up_at date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, job_id)
);

create index if not exists applications_user_status_updated_idx on public.applications(user_id, status, updated_at desc);

alter table public.applications enable row level security;

drop policy if exists "Users can read own applications" on public.applications;
create policy "Users can read own applications"
on public.applications for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own applications" on public.applications;
create policy "Users can insert own applications"
on public.applications for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own applications" on public.applications;
create policy "Users can update own applications"
on public.applications for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own applications" on public.applications;
create policy "Users can delete own applications"
on public.applications for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.application_packages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  application_id uuid not null references public.applications(id) on delete cascade,
  job_id text not null,
  model text not null,
  fact_lock_passed boolean not null default false,
  package jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists application_packages_user_job_created_idx on public.application_packages(user_id, job_id, created_at desc);

alter table public.application_packages enable row level security;

drop policy if exists "Users can read own application packages" on public.application_packages;
create policy "Users can read own application packages"
on public.application_packages for select
to authenticated
using (auth.uid() = user_id);

-- Package writes are performed by the protected prepare-application Edge Function using the secret/service key.
